import org.antlr.v4.runtime.*;
import org.antlr.v4.runtime.tree.*;
import org.antlr.v4.runtime.CharStreams;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

public class main {
    public static void main(String[] args) throws IOException{

	// we expect exactly one argument: the name of the input file
	if (args.length!=1) {
	    System.err.println("\n");
	    System.err.println("Impl Interpreter\n");
	    System.err.println("=================\n\n");
	    System.err.println("Please give as input argument a filename\n");
	    System.exit(-1);
	}
	String filename=args[0];

	// open the input file
	CharStream input = CharStreams.fromFileName(filename);
	    //new ANTLRFileStream (filename); // depricated
	
	// create a lexer/scanner
	implLexer lex = new implLexer(input);
	
	// get the stream of tokens from the scanner
	CommonTokenStream tokens = new CommonTokenStream(lex);
	
	// create a parser
	implParser parser = new implParser(tokens);
	
	// and parse anything from the grammar for "start"
	ParseTree parseTree = parser.start();

	// Construct an interpreter and run it on the parse tree
	Interpreter interpreter = new Interpreter();
		AST result=interpreter.visit(parseTree);
    }
}

// We write an interpreter that implements interface
// "implVisitor<T>" that is automatically generated by ANTLR
// This is parameterized over a return type "<T>" which is in our case
// simply a Double.

class Interpreter extends AbstractParseTreeVisitor<AST> implements implVisitor<AST> {

    public AST visitStart(implParser.StartContext ctx){return new Start ();




	}

	@Override
	public AST visitHardware(implParser.HardwareContext ctx) {return new Hardware(ctx.id.getText());}
	@Override
	public AST visitInputs(implParser.InputsContext ctx)
	{
		List<String>id = new ArrayList<String>();
		for (Token t : ctx.id)
			id.add(t.getText());
		return new Inputs(id);}
	@Override
	public AST visitOutputs(implParser.OutputsContext ctx)
	{
		List<String>id = new ArrayList<String>();
		for (Token t : ctx.id)
			id.add(t.getText());
		return new Inputs(id);}



	@Override
	public AST visitLatchDec(implParser.LatchDecContext ctx) {return new LatchDec(ctx.id1.getText(),ctx.id2.getText());}

	@Override
	public AST visitUpdate(implParser.UpdateContext ctx) {return null;}
	@Override
	public AST visitUpdateDec(implParser.UpdateDecContext ctx) {return null;}
	@Override
	public AST visitSimulate(implParser.SimulateContext ctx) {return null;}
	@Override
	public AST visitSimlnp(implParser.SimlnpContext ctx) {return null;}
	@Override
	public AST visitCondition(implParser.ConditionContext ctx) {
		return null;
	}
	@Override
	public AST visitParantheses(implParser.ParanthesesContext ctx) {
		return null;
	}
	@Override
	public AST visitSignal(implParser.SignalContext ctx) {
		return null;
	}
	@Override
	public AST visitVariable(implParser.VariableContext ctx) {
		return null;
	}
	@Override
	public AST visitNegation(implParser.NegationContext ctx) {
		return null;
	}

	@Override
	public AST visitConst(implParser.ConstContext ctx) {return null;}
	@Override
	public AST visitExpr(implParser.ExprContext ctx) {return null;}


}

